/* GENERATED by scripts/build-client.mjs - do not edit. */
window.__ModuleLoader__.load({
  id: 'dsh-offpeak',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    const React = require('react')

    var plugin = (() => {
const MINUTES_PER_DAY = 1440
const formatters = new Map()

const formatterFor = (zone) => {
  let formatter = formatters.get(zone)
  if (!formatter) {
    formatter = new Intl.DateTimeFormat('en-US', {
      timeZone: zone,
      hour12: false,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    })
    formatters.set(zone, formatter)
  }
  return formatter
}

const isValidZone = (zone) => {
  if (typeof zone !== 'string' || zone.length === 0) return false
  try {
    formatterFor(zone).format(new Date())
    return true
  } catch {
    return false
  }
}

const parseHHMM = (value) => {
  if (typeof value !== 'string') return null
  const match = /^(\d{1,2}):(\d{2})$/.exec(value.trim())
  if (!match) return null
  const hours = Number(match[1])
  const minutes = Number(match[2])
  if (hours > 23 || minutes > 59) return null
  return hours * 60 + minutes
}

const formatHHMM = (minutes) => {
  const normalized = ((minutes % MINUTES_PER_DAY) + MINUTES_PER_DAY) % MINUTES_PER_DAY
  return `${String(Math.floor(normalized / 60)).padStart(2, '0')}:${String(normalized % 60).padStart(2, '0')}`
}

const formatOffset = (minutes) => {
  const sign = minutes < 0 ? '-' : '+'
  const absolute = Math.abs(Math.round(minutes))
  return `${sign}${String(Math.floor(absolute / 60)).padStart(2, '0')}:${String(absolute % 60).padStart(2, '0')}`
}

const wallClock = (zone, date) => {
  const parts = {}
  for (const part of formatterFor(zone).formatToParts(date)) parts[part.type] = part.value
  const y = Number(parts.year)
  const mo = Number(parts.month)
  const d = Number(parts.day)
  // Some ICU builds report midnight as hour "24"; fold it back.
  const minutes = (Number(parts.hour) % 24) * 60 + Number(parts.minute)
  return { y, mo, d, weekday: new Date(Date.UTC(y, mo - 1, d)).getUTCDay(), minutes }
}

const isoWeekday = (weekday) => (weekday === 0 ? 7 : weekday)

const dayKey = (y, mo, d) =>
  `${String(y).padStart(4, '0')}-${String(mo).padStart(2, '0')}-${String(d).padStart(2, '0')}`

const addDays = (y, mo, d, delta) => {
  const shifted = new Date(Date.UTC(y, mo - 1, d + delta))
  return { y: shifted.getUTCFullYear(), mo: shifted.getUTCMonth() + 1, d: shifted.getUTCDate() }
}

// Every instant with this wall reading: none in a DST gap, two in a repeat.
const wallToInstants = (zone, y, mo, d, minutes) => {
  const naive = Date.UTC(y, mo - 1, d) + minutes * 60000

  // Sampled across a few days so both sides of a DST change are seen.
  const offsets = new Set()
  for (const day of [-2, -1, 0, 1, 2]) {
    offsets.add(utcOffsetMinutes(zone, naive + day * MINUTES_PER_DAY * 60000))
  }

  const found = []
  for (const offset of offsets) {
    const candidate = naive - offset * 60000
    const wc = wallClock(zone, new Date(candidate))
    if (wc.y === y && wc.mo === mo && wc.d === d && wc.minutes === minutes) found.push(candidate)
  }
  return found
}

// One instant for a wall reading: past a DST gap, the earlier one in a repeat.
const wallToInstant = (zone, y, mo, d, minutes) => {
  const found = wallToInstants(zone, y, mo, d, minutes)
  if (found.length > 0) return Math.min(...found)
  for (let step = 1; step <= 180; step += 1) {
    const after = wallToInstants(zone, y, mo, d, minutes + step)
    if (after.length > 0) return Math.min(...after)
  }
  return null
}

// Half-open [pauseAt, resumeAt); a crossing window belongs to its start day.
const windowMatchesAt = (window, wall, activeDays) => {
  const pauseAt = parseHHMM(window.pauseAt)
  const resumeAt = parseHHMM(window.resumeAt)
  if (pauseAt === null || resumeAt === null || pauseAt === resumeAt) return false

  const crossesMidnight = pauseAt > resumeAt
  const inWindow = crossesMidnight
    ? wall.minutes >= pauseAt || wall.minutes < resumeAt
    : wall.minutes >= pauseAt && wall.minutes < resumeAt
  if (!inWindow) return false

  const startedToday = !crossesMidnight || wall.minutes >= pauseAt
  const startWeekday = startedToday
    ? isoWeekday(wall.weekday)
    : isoWeekday((wall.weekday + 6) % 7)

  if (Array.isArray(window.days) && window.days.length > 0) {
    return window.days.includes(startWeekday)
  }
  return !Array.isArray(activeDays) || activeDays.length === 0 || activeDays.includes(startWeekday)
}

const startOfWindowOnDay = (zone, y, mo, d, pauseAt) => {
  const at = wallToInstant(zone, y, mo, d, pauseAt)
  return at === null ? null : { at, day: dayKey(y, mo, d) }
}

// Next pause at or after now, scanning ahead so sparse weekdays are found.
const nextPause = (now, config, limitDays = 8) => {
  const zone = config.scheduleZone
  if (!isValidZone(zone)) return null
  const wall = wallClock(zone, now)
  let best = null

  for (let delta = 0; delta <= limitDays; delta += 1) {
    const day = addDays(wall.y, wall.mo, wall.d, delta)
    const weekday = isoWeekday(new Date(Date.UTC(day.y, day.mo - 1, day.d)).getUTCDay())
    if (Array.isArray(config.activeDays) && config.activeDays.length > 0 && !config.activeDays.includes(weekday)) {
      continue
    }
    for (const window of config.windows ?? []) {
      if (Array.isArray(window.days) && window.days.length > 0 && !window.days.includes(weekday)) continue
      const pauseAt = parseHHMM(window.pauseAt)
      if (pauseAt === null) continue
      const start = startOfWindowOnDay(zone, day.y, day.mo, day.d, pauseAt)
      if (!start || start.at < now) continue
      if (!best || start.at < best.at) best = { window, at: start.at, day: start.day }
    }
    if (best && delta > 0) break
  }

  return best
}

const utcOffsetMinutes = (zone, instant) => {
  const date = new Date(Math.floor(instant / 60000) * 60000)
  const wall = wallClock(zone, date)
  const asUTC = Date.UTC(wall.y, wall.mo - 1, wall.d, Math.floor(wall.minutes / 60), wall.minutes % 60)
  return Math.round((asUTC - date.getTime()) / 60000)
}

const observesDST = (zone, year = new Date().getUTCFullYear()) => {
  if (!isValidZone(zone)) return false
  const january = utcOffsetMinutes(zone, Date.UTC(year, 0, 15))
  const july = utcOffsetMinutes(zone, Date.UTC(year, 6, 15))
  return january !== july
}

// Holds the instant fixed at `reference` while the wall clock moves.
const convertHHMM = (fromZone, toZone, value, reference = Date.now()) => {
  const minutes = parseHHMM(value)
  if (minutes === null || !isValidZone(fromZone) || !isValidZone(toZone)) return value
  const at = new Date(reference)
  const wall = wallClock(fromZone, at)
  const instant = wallToInstant(fromZone, wall.y, wall.mo, wall.d, minutes)
  if (instant === null) return value
  return formatHHMM(wallClock(toZone, new Date(instant)).minutes)
}

// Beijing weekday peaks, with a margin to avoid boundary slip.
const DEEPSEEK_PEAK_PRESET = {
  zone: 'Asia/Shanghai',
  days: [1, 2, 3, 4, 5],
  windows: [
    { id: 'peak-am', pauseAt: '08:58', resumeAt: '12:02' },
    { id: 'peak-pm', pauseAt: '13:58', resumeAt: '18:02' },
  ],
}

// Preset converted into `targetZone`, never overriding the user's zone.
const presetWindowsFor = (targetZone, reference = Date.now()) =>
  DEEPSEEK_PEAK_PRESET.windows.map((window) => ({
    ...window,
    pauseAt: convertHHMM(DEEPSEEK_PEAK_PRESET.zone, targetZone, window.pauseAt, reference),
    resumeAt: convertHHMM(DEEPSEEK_PEAK_PRESET.zone, targetZone, window.resumeAt, reference),
    days: [...DEEPSEEK_PEAK_PRESET.days],
  }))

// Whole-hour offsets -11..+14 plus the half- and quarter-hour ones.
const SCHEDULE_ZONE_CHOICES = [
  'Pacific/Pago_Pago',
  'Pacific/Honolulu',
  'Pacific/Gambier',
  'America/Anchorage',
  'Pacific/Pitcairn',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Chicago',
  'Pacific/Galapagos',
  'America/New_York',
  'America/Bogota',
  'America/Halifax',
  'America/Caracas',
  'America/St_Johns',
  'America/Sao_Paulo',
  'America/Noronha',
  'Atlantic/Azores',
  'Atlantic/Cape_Verde',
  'UTC',
  'Europe/London',
  'Africa/Accra',
  'Europe/Paris',
  'Africa/Lagos',
  'Europe/Athens',
  'Africa/Johannesburg',
  'Europe/Moscow',
  'Africa/Nairobi',
  'Asia/Tehran',
  'Asia/Dubai',
  'Asia/Baku',
  'Asia/Kabul',
  'Asia/Karachi',
  'Asia/Yekaterinburg',
  'Asia/Kolkata',
  'Asia/Colombo',
  'Asia/Kathmandu',
  'Asia/Dhaka',
  'Asia/Omsk',
  'Asia/Yangon',
  'Asia/Bangkok',
  'Asia/Jakarta',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Makassar',
  'Australia/Eucla',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Australia/Darwin',
  'Australia/Brisbane',
  'Australia/Sydney',
  'Australia/Lord_Howe',
  'Pacific/Guadalcanal',
  'Pacific/Noumea',
  'Asia/Kamchatka',
  'Pacific/Auckland',
  'Pacific/Chatham',
  'Pacific/Tongatapu',
  'Pacific/Kiritimati',
]

const occurrenceId = (window, day) => `${window.id || window.pauseAt}|${day}`

// Shared by host and client so the notice and the gate cannot disagree.
const computeState = (now, config) => {
  if (!config || !config.enabled) return { state: 'NORMAL', reason: 'disabled' }

  const zone = config.scheduleZone
  if (!isValidZone(zone)) return { state: 'NORMAL', reason: 'bad-zone' }

  const wall = wallClock(zone, now)
  const today = dayKey(wall.y, wall.mo, wall.d)

  for (const window of config.windows ?? []) {
    if (!windowMatchesAt(window, wall, config.activeDays)) continue
    const id = occurrenceId(window, today)
    const resumeAt = parseHHMM(window.resumeAt)
    const pauseAt = parseHHMM(window.pauseAt)
    // A crossing window's evening half resumes tomorrow, its morning half today.
    const resumeDay =
      pauseAt > resumeAt && wall.minutes >= pauseAt
        ? addDays(wall.y, wall.mo, wall.d, 1)
        : { y: wall.y, mo: wall.mo, d: wall.d }
    const resumeAtInstant = wallToInstant(zone, resumeDay.y, resumeDay.mo, resumeDay.d, resumeAt)
    return {
      state: 'PAUSED',
      reason: 'in-window',
      window,
      occurrenceId: id,
      resumeAt: resumeAtInstant,
      minutesUntilResume: resumeAtInstant === null ? null : Math.ceil((resumeAtInstant - now) / 60000),
    }
  }

  // Checked after the windows, so one that started yesterday still wins.
  if (Array.isArray(config.activeDays) && config.activeDays.length > 0) {
    if (!config.activeDays.includes(isoWeekday(wall.weekday))) {
      return { state: 'NORMAL', reason: 'weekday-off' }
    }
  }

  const upcoming = nextPause(now, config)
  if (upcoming) {
    const minutesUntil = Math.ceil((upcoming.at - now) / 60000)
    if (minutesUntil <= config.warnMinutes) {
      const id = occurrenceId(upcoming.window, upcoming.day)
      return {
        state: 'WARN',
        reason: 'approaching',
        window: upcoming.window,
        occurrenceId: id,
        startsAt: upcoming.at,
        minutesUntil,
      }
    }
  }

  return { state: 'NORMAL', reason: 'no-window' }
}

const BUCKET_MS = 10 * 60 * 1000
const WINDOW_BUCKETS = 48

const isDrop = (previous, sample) => previous !== null && sample.total < previous.total

// Spend sums balance drops, so a top-up cannot cancel real spend.
const spendInWindow = (samples, now, windowMs) => {
  const from = now - windowMs
  let spend = 0
  let previous = null
  for (const sample of samples) {
    if (sample.at < from) {
      previous = sample
      continue
    }
    if (isDrop(previous, sample)) spend += previous.total - sample.total
    previous = sample
  }
  return spend
}

// One bar per bucket, oldest first; null means no sample.
const spendBars = (samples, now, buckets = WINDOW_BUCKETS, bucketMs = BUCKET_MS) => {
  const bars = new Array(buckets).fill(null)
  let previous = null

  for (const sample of samples) {
    if (isDrop(previous, sample)) {
      const index = buckets - 1 - Math.floor((now - sample.at) / bucketMs)
      if (index >= 0 && index < buckets) bars[index] = (bars[index] ?? 0) + (previous.total - sample.total)
    }
    previous = sample
  }

  return bars
}

const bucketLabel = (index, now, buckets = WINDOW_BUCKETS, bucketMs = BUCKET_MS) => {
  const at = now - (buckets - 1 - index) * bucketMs
  const date = new Date(at)
  return `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`
}

const formatClock = (instant) => {
  const date = new Date(instant)
  return `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`
}

// The `HH:MM-HH:MM` span a spend window covers.
const windowRangeLabel = (now, windowMs) => `${formatClock(now - windowMs)}-${formatClock(now)}`

// Unknown codes show their code; a wrong symbol would misstate the amount.
const SYMBOLS = { CNY: '¥', USD: '$' }

const currencySymbol = (currency) =>
  typeof currency === 'string' ? SYMBOLS[currency.trim().toUpperCase()] ?? '' : ''

// The symbol is the currency's own: a CNY figure never wears a dollar sign.
const formatMoney = (value, currency) => {
  // `?? 0` is not enough: Number('x') is NaN and renders as "NaN".
  const numeric = Number(value)
  const amount = (Number.isFinite(numeric) ? numeric : 0).toFixed(2)
  const symbol = currencySymbol(currency)
  if (symbol !== '') return `${symbol}${amount}`
  const code = typeof currency === 'string' ? currency.trim().toUpperCase() : ''
  return code === '' ? amount : `${amount} ${code}`
}

// Rate from the API's currency to the one shown; 1 means relabel only.
const conversionRate = (apiCurrency, displayCurrency, cnyPerUsd) => {
  const from = typeof apiCurrency === 'string' ? apiCurrency.trim().toUpperCase() : ''
  const to = typeof displayCurrency === 'string' ? displayCurrency.trim().toUpperCase() : ''
  const rate = Number(cnyPerUsd)
  if (!(rate > 0) || from === '' || to === '' || from === to) return 1
  if (from === 'USD' && to === 'CNY') return rate
  if (from === 'CNY' && to === 'USD') return 1 / rate
  return 1
}

const fallbackLocale = 'en'

const dictionaries = {
  en: {
    sectionLabel: 'Off-peak',
    title: 'Off-peak pause',
    subtitle:
      'Holds model calls during DeepSeek peak hours so they are sent at off-peak prices. Nothing is sent while paused.',
    enable: 'Enable off-peak pause',
    enableAction: 'Enable',
    disableAction: 'Disable',
    scheduleZone: 'Schedule time zone',
    scheduleZoneHint:
      'The zone your pause windows are written in. Peak pricing is defined in Beijing time; the preset converts those hours into whichever zone you pick here.',
    scheduleZonePinned: 'Pinned to Beijing time, where peak pricing is defined. This never drifts.',
    dstWarning:
      '{zone} shifts for daylight saving, so these windows will move relative to Beijing peak twice a year.',
    pinToPricingZone: 'Express in Beijing time instead',
    displayZone: 'Show times in',
    displayZoneSchedule: 'Schedule zone',
    displayZoneBrowser: 'My time zone',
    localTime: 'your time',
    windows: 'Pause windows',
    windowsEmpty: 'No windows yet. Add one, or apply the DeepSeek preset below.',
    addWindow: 'Add window',
    remove: 'Remove',
    pauseAt: 'Pause at',
    resumeAt: 'Resume at',
    days: 'Days',
    applyPreset: 'Apply DeepSeek peak hours',
    presetNote:
      'Beijing 09:00-12:00 and 14:00-18:00, weekdays only, with a two-minute margin, converted into your schedule zone.',
    presetAdded: 'Added {count} window(s) in {zone}. Not saved yet.',
    presetExists: 'Those windows are already in the list.',
    activeDays: 'Days that pause',
    activeDaysHint: 'Weekends are billed off-peak, so they are excluded by default.',
    warnMinutes: 'Warn before pause (minutes)',
    routeFilter: 'Applies to',
    routeAll: 'All model calls',
    routeDeepSeek: 'DeepSeek official routes only',
    showBalance: 'Show API balance',
    showBalanceHint: 'Reads the DeepSeek account balance with your stored API key. The key never leaves the host.',
    currency: 'Balance currency',
    currencyAuto: 'Follow the API',
    currencyHint:
      'The balance API reports your account in its own currency. Choosing another one changes the symbol only, unless you also set a rate below.',
    cnyPerUsd: 'CNY per USD',
    cnyPerUsdHint: 'Set a rate, for example 7.2, to convert the API figure. 0 keeps the figure as the API reported it.',
    showStatus: 'Show the status in the header',
    showStatusHint: 'Turn this off to hide the off-peak entry from the conversation header entirely.',
    chartTitle: 'Spend, last 8 h (per 10 min)',
    chartNoData: 'no sample',
    chartCollecting: 'Collecting samples - no spend recorded yet.',
    granted: 'granted',
    toppedUp: 'topped-up',
    spent10m: 'spent 10m',
    spent1h: 'spent 1h',
    spent24h: 'spent 24h',
    chartNote: 'Estimated from balance samples; official billing takes precedence.',
    save: 'Save',
    saved: 'Saved',
    saveFailed: 'Could not save',
    dirty: 'Unsaved changes',
    statusLine: 'offpeak: {status}',
    statusLoading: 'loading',
    statusUnavailable: 'unavailable',
    statusDisabled: 'off',
    statusWaiting: 'waiting for peak hours',
    statusOffPeakDay: 'off-peak day',
    statusWarn: 'pausing in {minutes} min',
    statusPaused: 'paused until {time}',
    balance: 'Balance',
    dismiss: 'Dismiss',
    bannerPaused: 'Model calls are held until {time} to avoid peak pricing.',
    bannerWarn: 'Peak hours start in {minutes} min. Model calls will be held.',
    monday: 'Mon',
    tuesday: 'Tue',
    wednesday: 'Wed',
    thursday: 'Thu',
    friday: 'Fri',
    saturday: 'Sat',
    sunday: 'Sun',
  },
  zh: {
    sectionLabel: '低谷时段',
    title: '低谷时段暂停',
    subtitle: '在 DeepSeek 高峰时段暂缓模型调用，待低谷价格时再发送。暂停期间不会发出任何请求。',
    enable: '启用低谷时段暂停',
    enableAction: '启用',
    disableAction: '停用',
    scheduleZone: '计划时区',
    scheduleZoneHint: '暂停时段的书写时区。高峰定价以北京时间为准；预设会把该时段换算到你在这里选择的时区。',
    scheduleZonePinned: '固定为北京时间（高峰定价的定义时区），不会随夏令时漂移。',
    dstWarning: '{zone} 实行夏令时，因此这些时段每年会有两次相对北京高峰时段发生偏移。',
    pinToPricingZone: '改为按北京时间表示',
    displayZone: '时间显示时区',
    displayZoneSchedule: '计划时区',
    displayZoneBrowser: '我的时区',
    localTime: '你的时间',
    windows: '暂停时段',
    windowsEmpty: '还没有时段。添加一个，或在下方应用 DeepSeek 预设。',
    addWindow: '添加时段',
    remove: '移除',
    pauseAt: '暂停于',
    resumeAt: '恢复于',
    days: '星期',
    applyPreset: '应用 DeepSeek 高峰时段',
    presetNote: '北京时间 09:00-12:00 与 14:00-18:00，仅工作日，含两分钟余量，已换算到你的计划时区。',
    presetAdded: '已在 {zone} 添加 {count} 个时段。尚未保存。',
    presetExists: '这些时段已在列表中。',
    activeDays: '暂停的星期',
    activeDaysHint: '周末按低谷计价，因此默认不包含。',
    warnMinutes: '暂停前提醒（分钟）',
    routeFilter: '适用范围',
    routeAll: '所有模型调用',
    routeDeepSeek: '仅 DeepSeek 官方线路',
    showBalance: '显示 API 余额',
    showBalanceHint: '使用已保存的 API 密钥读取 DeepSeek 账户余额。密钥不会离开主机。',
    currency: '余额货币',
    currencyAuto: '跟随 API',
    currencyHint: '余额 API 按你账户自身的货币返回金额。若选择其他货币，则只更改符号；如需换算，请在下方设置汇率。',
    cnyPerUsd: '每美元兑人民币',
    cnyPerUsdHint: '设置汇率（例如 7.2）以换算 API 金额；设为 0 则按 API 返回的金额原样显示。',
    showStatus: '在页眉显示状态',
    showStatusHint: '关闭后将从对话页眉中完全移除低谷时段条目。',
    chartTitle: '近 8 小时支出（每 10 分钟）',
    chartNoData: '无采样',
    chartCollecting: '正在采集采样 - 尚未记录到支出。',
    granted: '赠送',
    toppedUp: '充值',
    spent10m: '10 分钟支出',
    spent1h: '1 小时支出',
    spent24h: '24 小时支出',
    chartNote: '根据余额采样估算；以官方账单为准。',
    save: '保存',
    saved: '已保存',
    saveFailed: '保存失败',
    dirty: '有未保存的更改',
    statusLine: '低谷时段：{status}',
    statusLoading: '加载中',
    statusUnavailable: '不可用',
    statusDisabled: '已关闭',
    statusWaiting: '等待高峰时段',
    statusOffPeakDay: '低谷日',
    statusWarn: '{minutes} 分钟后暂停',
    statusPaused: '已暂停，至 {time}',
    balance: '余额',
    dismiss: '隐藏',
    bannerPaused: '为避免高峰定价，模型调用将挂起至 {time}。',
    bannerWarn: '高峰时段将在 {minutes} 分钟后开始，届时模型调用会被挂起。',
    monday: '周一',
    tuesday: '周二',
    wednesday: '周三',
    thursday: '周四',
    friday: '周五',
    saturday: '周六',
    sunday: '周日',
  },
}

const translate = (locale, key, vars) => {
  const language = String(locale ?? fallbackLocale)
  const dict = dictionaries[language] ?? dictionaries[language.split('-')[0]] ?? dictionaries[fallbackLocale]
  let text = dict[key] ?? dictionaries[fallbackLocale][key] ?? key
  if (vars) {
    for (const [name, value] of Object.entries(vars)) text = text.split(`{${name}}`).join(String(value))
  }
  return text
}

const NS = 'offpeak'
const h = React.createElement

const WEEKDAY_KEYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']


const TONE = {
  disabled: 'var(--dsw-alias-label-tertiary)',
  idle: 'var(--dsw-alias-state-success-primary)',
  warn: 'var(--dsw-alias-state-warn-primary)',
  paused: 'var(--dsw-alias-state-error-primary)',
}

const toneFor = (state) => {
  if (state.state === 'PAUSED') return TONE.paused
  if (state.state === 'WARN') return TONE.warn
  if (state.reason === 'disabled' || state.reason === 'bad-zone') return TONE.disabled
  return TONE.idle
}

const browserZone = () => {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
  } catch {
    return 'UTC'
  }
}

// The schedule time in the viewer's zone, for the "your time" note.
const localTimeFor = (scheduleZone, hhmm, viewerZone) => {
  const minutes = parseHHMM(hhmm)
  if (minutes === null || !isValidZone(scheduleZone) || !isValidZone(viewerZone)) return ''
  const wall = wallClock(scheduleZone, new Date())
  const instant = wallToInstant(scheduleZone, wall.y, wall.mo, wall.d, minutes)
  if (instant === null) return ''
  return formatHHMM(wallClock(viewerZone, new Date(instant)).minutes)
}

const formatBalance = (balance, money) =>
  balance && balance.total !== null && balance.total !== undefined ? money(balance.total) : ''

const describe = (state, config, t) => {
  if (state.state === 'PAUSED') {
    const resume =
      state.resumeAt === null || state.resumeAt === undefined
        ? null
        : wallClock(config.scheduleZone, new Date(state.resumeAt)).minutes
    return t('statusPaused', { time: resume === null ? '?' : formatHHMM(resume) })
  }
  if (state.state === 'WARN') return t('statusWarn', { minutes: state.minutesUntil })
  if (state.reason === 'disabled') return t('statusDisabled')
  if (state.reason === 'weekday-off') return t('statusOffPeakDay')
  return t('statusWaiting')
}

// The scope's own status word arrives in English before it resolves.
const describeAvailability = (status, t) => {
  if (status === 'loading') return t('statusLoading')
  if (status === 'unavailable') return t('statusUnavailable')
  return status
}

const useScope = (scope) =>
  React.useSyncExternalStore(
    (onChange) => scope.subscribe(onChange),
    () => scope.getSnapshot(),
  )

const useNow = (intervalMs) => {
  const [now, setNow] = React.useState(() => Date.now())
  React.useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), intervalMs)
    return () => clearInterval(id)
  }, [intervalMs])
  return now
}

const useLocaleId = (locale) => {
  const subscribe = React.useCallback(
    (onChange) => (locale && locale.subscribe ? locale.subscribe(onChange) : () => {}),
    [locale],
  )
  const read = React.useCallback(() => {
    try {
      return locale?.getSnapshot?.().active ?? fallbackLocale
    } catch {
      return fallbackLocale
    }
  }, [locale])
  return React.useSyncExternalStore(subscribe, read)
}

const currentLocaleId = (locale) => {
  try {
    return locale?.getSnapshot?.().active ?? fallbackLocale
  } catch {
    return fallbackLocale
  }
}

const styles = {
  // Inline, never fixed, so it cannot mask other chrome.
  entry: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  chart: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    zIndex: 70,
    width: '340px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '12px',
    borderRadius: '10px',
    background: 'var(--dsw-alias-bg-layer-3)',
    border: '1px solid var(--dsw-alias-border-l2)',
    boxShadow: '0 8px 24px rgba(0,0,0,0.28)',
  },
  chartHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px' },
  bars: { display: 'flex', alignItems: 'flex-end', gap: '2px', height: '90px' },
  emptyChart: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '90px',
    borderRadius: '8px',
    border: '1px dashed var(--dsw-alias-border-l2)',
    color: 'var(--dsw-alias-label-tertiary)',
    fontSize: '12px',
  },
  bar: { flex: '1 1 0', minHeight: '2px', borderRadius: '2px 2px 0 0' },
  spends: { display: 'flex', flexDirection: 'column', gap: '2px', fontSize: '12px' },
  balanceWrap: { position: 'relative', display: 'inline-flex' },
  balance: {
    cursor: 'pointer',
    border: 'none',
    background: 'transparent',
    color: 'var(--dsw-alias-label-primary)',
    // Inherit so the figure matches the header text, not a small link.
    font: 'inherit',
    padding: 0,
  },
  bubble: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    zIndex: 70,
    width: '270px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '10px 12px',
    borderRadius: '10px',
    fontSize: '12px',
    background: 'var(--dsw-alias-bg-layer-3)',
    color: 'var(--dsw-alias-label-primary)',
    border: '1px solid var(--dsw-alias-border-l2)',
    boxShadow: '0 8px 24px rgba(0,0,0,0.28)',
    pointerEvents: 'none',
  },
  pill: {
    pointerEvents: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    borderRadius: '999px',
    fontSize: '12px',
    background: 'var(--dsw-alias-bg-layer-2)',
    color: 'var(--dsw-alias-label-primary)',
    border: '1px solid var(--dsw-alias-border-l1)',
  },
  banner: {
    pointerEvents: 'auto',
    maxWidth: '420px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '10px 14px',
    borderRadius: '10px',
    fontSize: '12px',
    background: 'var(--dsw-alias-bg-layer-3)',
    color: 'var(--dsw-alias-label-primary)',
    border: '1px solid var(--dsw-alias-border-l2)',
  },
  bannerActions: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  chip: {
    pointerEvents: 'auto',
    // Flex with a gap: inline content would glue the buttons to the message.
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    padding: '4px 12px',
    borderRadius: '999px',
    fontSize: '12px',
    background: 'var(--dsw-alias-bg-layer-2)',
    color: 'var(--dsw-alias-label-secondary)',
    border: '1px solid var(--dsw-alias-border-l1)',
  },
  button: {
    cursor: 'pointer',
    fontSize: '12px',
    padding: '3px 10px',
    borderRadius: '6px',
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-layer-2)',
    color: 'var(--dsw-alias-label-primary)',
  },
  primaryButton: {
    cursor: 'pointer',
    fontSize: '12px',
    padding: '3px 10px',
    borderRadius: '6px',
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-button-primary-fill)',
    color: 'var(--dsw-alias-label-primary-foreground)',
  },
  error: { color: 'var(--dsw-alias-state-error-primary)' },
  dot: { width: '8px', height: '8px', borderRadius: '50%', flex: '0 0 auto' },
  page: { display: 'flex', flexDirection: 'column', gap: '18px', padding: '4px 2px', fontSize: '13px' },
  section: { display: 'flex', flexDirection: 'column', gap: '10px' },
  row: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '16px' },
  label: { color: 'var(--dsw-alias-label-primary)' },
  hint: { color: 'var(--dsw-alias-label-tertiary)', fontSize: '12px', marginTop: '2px' },
  control: {
    fontSize: '12px',
    padding: '4px 8px',
    borderRadius: '6px',
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-layer-2)',
    color: 'var(--dsw-alias-label-primary)',
  },
  windowCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid var(--dsw-alias-border-l1)',
    background: 'var(--dsw-alias-bg-layer-2)',
  },
  windowHead: { display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' },
  warnRow: { display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' },
  spacer: { flex: '1 1 auto' },
  days: { display: 'flex', gap: '4px', flexWrap: 'wrap' },
  dayToggle: (active) => ({
    cursor: 'pointer',
    fontSize: '11px',
    padding: '2px 7px',
    borderRadius: '5px',
    border: `1px solid ${active ? 'var(--dsw-alias-brand-primary)' : 'var(--dsw-alias-border-l2)'}`,
    background: active ? 'var(--dsw-alias-brand-primary)' : 'transparent',
    color: active ? 'var(--dsw-alias-label-primary-foreground)' : 'var(--dsw-alias-label-secondary)',
  }),
  divider: { height: '1px', background: 'var(--dsw-alias-border-l1)' },
}

function Switch({ checked, onChange, disabled }) {
  return h(
    'button',
    {
      type: 'button',
      role: 'switch',
      'aria-checked': checked,
      disabled,
      onClick: () => onChange(!checked),
      style: {
        width: '38px',
        height: '22px',
        padding: '2px',
        borderRadius: '999px',
        cursor: disabled ? 'default' : 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: checked ? 'flex-end' : 'flex-start',
        border: '1px solid var(--dsw-alias-border-l2)',
        background: checked ? 'var(--dsw-alias-brand-primary)' : 'var(--dsw-alias-bg-layer-3)',
        transition: 'background 120ms ease',
      },
    },
    h('span', {
      style: {
        width: '16px',
        height: '16px',
        borderRadius: '50%',
        background: checked ? 'var(--dsw-alias-label-primary-foreground)' : 'var(--dsw-alias-label-tertiary)',
        transition: 'background 120ms ease',
      },
    }),
  )
}

function Row({ label, hint, children }) {
  return h(
    'div',
    { style: styles.row },
    h('div', null, h('div', { style: styles.label }, label), hint ? h('div', { style: styles.hint }, hint) : null),
    h('div', { style: { display: 'flex', alignItems: 'center', gap: '8px' } }, children),
  )
}

function DayPicker({ value, onChange, t }) {
  return h(
    'div',
    { style: styles.days },
    WEEKDAY_KEYS.map((key, index) => {
      const day = index + 1
      const active = (value ?? []).includes(day)
      return h(
        'button',
        {
          key,
          type: 'button',
          style: styles.dayToggle(active),
          onClick: () => onChange(active ? value.filter((entry) => entry !== day) : [...(value ?? []), day].sort()),
        },
        t(key),
      )
    }),
  )
}

// Page-scoped: a session switch remounts the entry, a reload does not.
let dismissedOccurrence = null

// Page-scoped too: a rebuilt entry starts from the last figures, no flicker.
const remembered = { balance: null, balanceError: '', chart: null }

function HeaderEntry({ scope, locale, connection }) {
  const snapshot = useScope(scope)
  const localeId = useLocaleId(locale)
  const t = (key, vars) => translate(localeId, key, vars)
  const now = useNow(1000)

  const [dismissedFor, setDismissedFor] = React.useState(dismissedOccurrence)
  const [error, setError] = React.useState('')
  const [busy, setBusy] = React.useState(false)
  const [balance, setBalance] = React.useState(remembered.balance)
  const [balanceError, setBalanceError] = React.useState(remembered.balanceError)
  const [chartOpen, setChartOpen] = React.useState(false)
  const [chartData, setChartData] = React.useState(remembered.chart)
  const [hoveringBalance, setHoveringBalance] = React.useState(false)

  const config = snapshot.value
  const ready = snapshot.status === 'ready' && config !== undefined
  const state = ready ? computeState(now, config) : { state: snapshot.status, reason: snapshot.status }

  const showBalance = ready && config.showBalance === true && connection !== undefined

  // A forced currency relabels; only a rate converts.
  const apiCurrency = chartData?.currency ?? balance?.currency ?? null
  const displayCurrency = ready && config.currency !== undefined && config.currency !== 'auto' ? config.currency : apiCurrency
  const rate = conversionRate(apiCurrency, displayCurrency, ready ? config.cnyPerUsd : 0)
  const money = (value) => formatMoney(value * rate, displayCurrency)

  // Written through to the page-scoped copy so the next mount starts from it.
  const rememberBalance = (value, message) => {
    remembered.balance = value
    remembered.balanceError = message
    setBalance(value)
    setBalanceError(message)
  }

  // Polled for the hover breakdown too, not only when the chart is open.
  React.useEffect(() => {
    if ((!showBalance && !chartOpen) || connection === undefined) return undefined
    let cancelled = false
    const load = async () => {
      try {
        const result = await connection.rpc.call('/offpeak', 'history', null)
        if (!cancelled && result.ok) {
          remembered.chart = result.value
          setChartData(result.value)
        }
      } catch {
        // keep the previous series rather than blanking the view
      }
    }
    void load()
    const id = setInterval(load, 60000)
    return () => {
      cancelled = true
      clearInterval(id)
    }
  }, [showBalance, chartOpen, connection])

  React.useEffect(() => {
    if (!showBalance) {
      rememberBalance(null, '')
      return undefined
    }
    let cancelled = false
    const load = async () => {
      try {
        const result = await connection.rpc.call('/offpeak', 'balance', null)
        if (cancelled) return
        if (result.ok) {
          rememberBalance(result.value, '')
        } else {
          rememberBalance(null, result.error.message)
        }
      } catch (cause) {
        if (!cancelled) rememberBalance(remembered.balance, String((cause && cause.message) || cause))
      }
    }
    void load()
    const id = setInterval(load, 300000)
    return () => {
      cancelled = true
      clearInterval(id)
    }
  }, [showBalance, connection])

  const bannerWorthy = ready && (state.state === 'PAUSED' || state.state === 'WARN')
  const showBanner = bannerWorthy && dismissedFor !== state.occurrenceId

  const run = async (action) => {
    setBusy(true)
    setError('')
    try {
      await action()
    } catch (cause) {
      setError(String((cause && cause.message) || cause))
    } finally {
      setBusy(false)
    }
  }

  if (ready && config.showStatus === false) return null

  const bars = chartData ? spendBars(chartData.samples, chartData.now, WINDOW_BUCKETS, BUCKET_MS) : null
  const peak = bars ? Math.max(...bars.map((value) => value ?? 0), 0.000001) : 1

  return h(
    'div',
    { style: styles.entry },
    h('span', null, t('statusLine', { status: ready ? describe(state, config, t) : describeAvailability(snapshot.status, t) })),
    // Trailing, so it separates the label from the balance.
    h('span', { style: { ...styles.dot, background: ready ? toneFor(state) : TONE.disabled } }),
    showBalance
      ? balance !== null
        ? h(
            'span',
            { style: styles.balanceWrap },
            h(
              'button',
              {
                type: 'button',
                style: styles.balance,
                onClick: () => setChartOpen((open) => !open),
                onMouseEnter: () => setHoveringBalance(true),
                onMouseLeave: () => setHoveringBalance(false),
              },
              formatBalance(balance, money),
            ),
            hoveringBalance && !chartOpen
              ? h(
                  'div',
                  { style: styles.bubble },
                  h(
                    'div',
                    null,
                    `${formatBalance(balance, money)} ${t('balance')}`,
                    balance.granted !== null || balance.toppedUp !== null
                      ? ` (${t('granted')} ${money(balance.granted)} · ${t('toppedUp')} ${money(balance.toppedUp)})`
                      : '',
                  ),
                  chartData
                    ? h(
                        'div',
                        { style: styles.spends },
                        h(
                          'span',
                          null,
                          `${t('spent10m')} ${money(chartData.spends.m10)} ${windowRangeLabel(chartData.now, 10 * 60 * 1000)}`,
                        ),
                        h(
                          'span',
                          null,
                          `${t('spent1h')} ${money(chartData.spends.h1)} ${windowRangeLabel(chartData.now, 60 * 60 * 1000)}`,
                        ),
                        h('span', null, `${t('spent24h')} ${money(chartData.spends.h24)}`),
                      )
                    : null,
                  h('div', { style: styles.hint }, t('chartNote')),
                )
              : null,
          )
        : balanceError !== ''
          ? h('span', { style: styles.error }, balanceError)
          : null
      : null,
    ready
      ? h(
          'button',
          {
            type: 'button',
            style: styles.button,
            disabled: busy,
            onClick: () => run(() => scope.set('enabled', !config.enabled)),
          },
          config.enabled ? t('disableAction') : t('enableAction'),
        )
      : null,
    showBanner
      ? h(
          'span',
          { style: styles.chip },
          state.state === 'PAUSED'
            ? t('bannerPaused', {
                time: state.resumeAt
                  ? formatHHMM(wallClock(config.scheduleZone, new Date(state.resumeAt)).minutes)
                  : '?',
              })
            : t('bannerWarn', { minutes: state.minutesUntil }),
          h(
            'button',
            {
              type: 'button',
              style: styles.button,
              onClick: () => {
                dismissedOccurrence = state.occurrenceId
                setDismissedFor(state.occurrenceId)
              },
            },
            t('dismiss'),
          ),
        )
      : null,
    error ? h('span', { style: styles.error }, error) : null,
    chartOpen && bars
      ? h(
          'div',
          { style: styles.chart },
          h(
            'div',
            { style: styles.chartHead },
            h('span', { style: styles.label }, t('chartTitle')),
            h('button', { type: 'button', style: styles.button, onClick: () => setChartOpen(false) }, '×'),
          ),
          bars.some((value) => value !== null)
            ? h(
                'div',
                { style: styles.bars },
                bars.map((value, index) =>
                  h('div', {
                    key: index,
                    title: `${bucketLabel(index, chartData.now, WINDOW_BUCKETS, BUCKET_MS)} · ${
                      value === null ? t('chartNoData') : money(value)
                    }`,
                    style: {
                      ...styles.bar,
                      height: `${Math.max(2, ((value ?? 0) / peak) * 100)}%`,
                      background: value === null ? 'var(--dsw-alias-border-l1)' : 'var(--dsw-alias-state-error-primary)',
                    },
                  }),
                ),
              )
            : h('div', { style: styles.emptyChart }, t('chartCollecting')),
          h(
            'div',
            { style: styles.spends },
            h('span', null, `${t('spent10m')} ${money(chartData.spends.m10)}`),
            h('span', null, `${t('spent1h')} ${money(chartData.spends.h1)}`),
            h('span', null, `${t('spent24h')} ${money(chartData.spends.h24)}`),
          ),
          h('div', { style: styles.hint }, t('chartNote')),
        )
      : null,
  )
}

const toDraft = (config) => ({
  windows: (config.windows ?? []).map((window) => ({ ...window })),
  scheduleZone: config.scheduleZone,
  displayZone: config.displayZone ?? 'schedule',
  activeDays: [...(config.activeDays ?? [])],
  warnMinutes: config.warnMinutes,
  routeFilter: config.routeFilter,
  currency: config.currency ?? 'auto',
  cnyPerUsd: config.cnyPerUsd ?? 0,
})

function SettingsPage({ scope, locale }) {
  const snapshot = useScope(scope)
  const localeId = useLocaleId(locale)
  const t = (key, vars) => translate(localeId, key, vars)
  const browser = React.useMemo(browserZone, [])

  const config = snapshot.value
  // Seeded from the config in hand so the first render is not a placeholder.
  const [draft, setDraft] = React.useState(() => (config ? toDraft(config) : null))
  const [dirty, setDirty] = React.useState(false)
  const [message, setMessage] = React.useState(null)
  const [busy, setBusy] = React.useState(false)

  React.useEffect(() => {
    if (!config || dirty) return
    setDraft(toDraft(config))
  }, [config, dirty])

  if (snapshot.status !== 'ready' || !config || !draft) {
    return h(
      'div',
      { style: styles.page },
      h('div', { style: styles.hint }, t('statusLine', { status: describeAvailability(snapshot.status, t) })),
    )
  }

  const patch = (changes) => {
    setDraft((current) => ({ ...current, ...changes }))
    setDirty(true)
    setMessage(null)
  }

  const viewerZone = draft.displayZone === 'browser' ? browser : draft.scheduleZone

  const writeImmediately = async (field, value) => {
    setMessage(null)
    try {
      await scope.set(field, value)
    } catch (cause) {
      setMessage({ kind: 'error', text: `${t('saveFailed')}: ${String((cause && cause.message) || cause)}` })
    }
  }

  const save = async () => {
    setBusy(true)
    setMessage(null)
    try {
      await scope.mutate([
        { op: 'set', path: ['windows'], value: draft.windows },
        { op: 'set', path: ['scheduleZone'], value: draft.scheduleZone },
        { op: 'set', path: ['displayZone'], value: draft.displayZone },
        { op: 'set', path: ['activeDays'], value: draft.activeDays },
        { op: 'set', path: ['warnMinutes'], value: Number(draft.warnMinutes) },
        { op: 'set', path: ['routeFilter'], value: draft.routeFilter },
        { op: 'set', path: ['currency'], value: draft.currency },
        { op: 'set', path: ['cnyPerUsd'], value: Number(draft.cnyPerUsd) },
      ])
      setDirty(false)
      setMessage({ kind: 'ok', text: t('saved') })
    } catch (cause) {
      setMessage({ kind: 'error', text: `${t('saveFailed')}: ${String((cause && cause.message) || cause)}` })
    } finally {
      setBusy(false)
    }
  }

  const addWindow = () =>
    patch({
      windows: [
        ...draft.windows,
        { id: `w${Date.now().toString(36)}`, pauseAt: '09:00', resumeAt: '12:00', days: [...draft.activeDays] },
      ],
    })

  const updateWindow = (index, changes) =>
    patch({ windows: draft.windows.map((window, at) => (at === index ? { ...window, ...changes } : window)) })

  const removeWindow = (index) => patch({ windows: draft.windows.filter((_, at) => at !== index) })

  // Adds the peak windows; the user's zone choice is not rewritten.
  const applyPreset = () => {
    const target = draft.scheduleZone
    const incoming = presetWindowsFor(target)
    const key = (window) => `${window.pauseAt}|${window.resumeAt}`
    const existing = new Set(draft.windows.map(key))
    const added = incoming.filter((window) => !existing.has(key(window)))

    patch({ windows: [...draft.windows, ...added] })
    setMessage({
      kind: 'ok',
      text: added.length > 0 ? t('presetAdded', { count: added.length, zone: target }) : t('presetExists'),
    })
  }

  const pinToPricingZone = () =>
    patch({
      scheduleZone: DEEPSEEK_PEAK_PRESET.zone,
      windows: draft.windows.map((window) => ({
        ...window,
        pauseAt: convertHHMM(draft.scheduleZone, DEEPSEEK_PEAK_PRESET.zone, window.pauseAt),
        resumeAt: convertHHMM(draft.scheduleZone, DEEPSEEK_PEAK_PRESET.zone, window.resumeAt),
      })),
    })

  const zoneOptions = [...new Set([draft.scheduleZone, browser, ...SCHEDULE_ZONE_CHOICES])]
    .filter(isValidZone)
    .map((zone) => ({ zone, offset: utcOffsetMinutes(zone, Date.now()) }))
    .sort((left, right) => left.offset - right.offset || left.zone.localeCompare(right.zone))

  const windowRows = draft.windows.length
    ? draft.windows.map((window, index) => {
        const localFrom = localTimeFor(draft.scheduleZone, window.pauseAt, viewerZone)
        const localTo = localTimeFor(draft.scheduleZone, window.resumeAt, viewerZone)
        return h(
          'div',
          { key: window.id ?? index, style: styles.windowCard },
          h(
            'div',
            { style: styles.windowHead },
            h('span', { style: styles.label }, `${window.pauseAt} - ${window.resumeAt}`),
            localFrom && localTo && viewerZone !== draft.scheduleZone
              ? h('span', { style: styles.hint }, `${localFrom} - ${localTo} ${t('localTime')}`)
              : null,
            h('span', { style: styles.spacer }),
            h('button', { type: 'button', style: styles.button, onClick: () => removeWindow(index) }, t('remove')),
          ),
          h(
            'div',
            { style: styles.windowHead },
            h('span', { style: styles.hint }, t('pauseAt')),
            h('input', {
              type: 'time',
              style: styles.control,
              value: window.pauseAt,
              onChange: (event) => updateWindow(index, { pauseAt: event.target.value }),
            }),
            h('span', { style: styles.hint }, t('resumeAt')),
            h('input', {
              type: 'time',
              style: styles.control,
              value: window.resumeAt,
              onChange: (event) => updateWindow(index, { resumeAt: event.target.value }),
            }),
          ),
          h(
            'div',
            { style: styles.windowHead },
            h('span', { style: styles.hint }, t('days')),
            h(DayPicker, { value: window.days, onChange: (days) => updateWindow(index, { days }), t }),
          ),
        )
      })
    : h('div', { style: styles.hint }, t('windowsEmpty'))

  return h(
    'div',
    { style: styles.page },
    h(
      'div',
      null,
      h('div', { style: { fontSize: '15px', fontWeight: 600 } }, t('title')),
      h('div', { style: styles.hint }, t('subtitle')),
    ),
    h(
      Row,
      { label: t('enable') },
      h(Switch, { checked: config.enabled, onChange: (value) => writeImmediately('enabled', value) }),
    ),
    h('div', { style: styles.divider }),
    h(
      'div',
      { style: styles.section },
      h(
        Row,
        {
          label: t('scheduleZone'),
          hint: draft.scheduleZone === DEEPSEEK_PEAK_PRESET.zone ? t('scheduleZonePinned') : t('scheduleZoneHint'),
        },
        h(
          'select',
          { style: styles.control, value: draft.scheduleZone, onChange: (event) => patch({ scheduleZone: event.target.value }) },
          zoneOptions.map((entry) =>
            h('option', { key: entry.zone, value: entry.zone }, `${entry.zone} (${formatOffset(entry.offset)})`),
          ),
        ),
      ),
      observesDST(draft.scheduleZone)
        ? h(
            'div',
            { style: styles.warnRow },
            h('span', { style: styles.hint }, t('dstWarning', { zone: draft.scheduleZone })),
            h('button', { type: 'button', style: styles.button, onClick: pinToPricingZone }, t('pinToPricingZone')),
          )
        : null,
      h(
        Row,
        { label: t('displayZone') },
        h(
          'select',
          { style: styles.control, value: draft.displayZone, onChange: (event) => patch({ displayZone: event.target.value }) },
          h('option', { value: 'schedule' }, t('displayZoneSchedule')),
          h('option', { value: 'browser' }, `${t('displayZoneBrowser')} (${browser}, ${formatOffset(utcOffsetMinutes(browser, Date.now()))})`),
        ),
      ),
    ),
    h('div', { style: styles.divider }),
    h(
      'div',
      { style: styles.section },
      h('div', { style: styles.label }, t('windows')),
      windowRows,
      h(
        'div',
        { style: { display: 'flex', gap: '8px', flexWrap: 'wrap' } },
        h('button', { type: 'button', style: styles.button, onClick: addWindow }, t('addWindow')),
        h('button', { type: 'button', style: styles.button, onClick: applyPreset }, t('applyPreset')),
      ),
      h('div', { style: styles.hint }, t('presetNote')),
    ),
    h('div', { style: styles.divider }),
    h(
      'div',
      { style: styles.section },
      h(
        Row,
        { label: t('activeDays'), hint: t('activeDaysHint') },
        h(DayPicker, { value: draft.activeDays, onChange: (days) => patch({ activeDays: days }), t }),
      ),
      h(
        Row,
        { label: t('warnMinutes') },
        h('input', {
          type: 'number',
          min: 0,
          style: { ...styles.control, width: '80px' },
          value: draft.warnMinutes,
          onChange: (event) => patch({ warnMinutes: event.target.value }),
        }),
      ),
      h(
        Row,
        { label: t('routeFilter') },
        h(
          'select',
          { style: styles.control, value: draft.routeFilter, onChange: (event) => patch({ routeFilter: event.target.value }) },
          h('option', { value: 'all' }, t('routeAll')),
          h('option', { value: 'deepseek-official' }, t('routeDeepSeek')),
        ),
      ),
      h(
        Row,
        { label: t('showBalance'), hint: t('showBalanceHint') },
        h(Switch, { checked: config.showBalance === true, onChange: (value) => writeImmediately('showBalance', value) }),
      ),
      h(
        Row,
        { label: t('currency'), hint: t('currencyHint') },
        h(
          'select',
          {
            style: styles.control,
            value: draft.currency,
            onChange: (event) => patch({ currency: event.target.value }),
          },
          h('option', { value: 'auto' }, t('currencyAuto')),
          h('option', { value: 'CNY' }, '¥ CNY'),
          h('option', { value: 'USD' }, '$ USD'),
        ),
      ),
      draft.currency === 'auto'
        ? null
        : h(
            Row,
            { label: t('cnyPerUsd'), hint: t('cnyPerUsdHint') },
            h('input', {
              type: 'number',
              min: 0,
              step: 0.01,
              style: { ...styles.control, width: '80px' },
              value: draft.cnyPerUsd,
              onChange: (event) => patch({ cnyPerUsd: Number(event.target.value) }),
            }),
          ),
      h(
        Row,
        { label: t('showStatus'), hint: t('showStatusHint') },
        h(Switch, { checked: config.showStatus !== false, onChange: (value) => writeImmediately('showStatus', value) }),
      ),
    ),
    h(
      'div',
      { style: { display: 'flex', alignItems: 'center', gap: '12px' } },
      h('button', { type: 'button', style: styles.primaryButton, disabled: busy || !dirty, onClick: save }, t('save')),
      dirty ? h('span', { style: styles.hint }, t('dirty')) : null,
      message ? h('span', { style: message.kind === 'error' ? styles.error : styles.hint }, message.text) : null,
    ),
  )
}

const inject = ['slots', 'settingsScope', 'locale']

function apply(ctx) {
  const slots = ctx.get('slots')
  const binder = ctx.get('settingsScope')
  const locale = ctx.get('locale')

  if (!slots || !binder) {
    console.error('[offpeak] client apply aborted; slots=', !!slots, 'settingsScope=', !!binder)
    return
  }

  const scope = binder.bind({ namespace: NS })

  slots.inject('conversation.session.header.utilities', () =>
    slots.register({ name: 'conversation.session.header.utilities', id: 'offpeak-status', order: 50 }, () =>
      h(HeaderEntry, { scope, locale, connection: ctx.get('connection') }),
    ),
  )

  slots.inject('settings.section', () =>
    slots.register(
      { name: 'settings.section', id: 'offpeak', order: 25, label: () => translate(currentLocaleId(locale), 'sectionLabel') },
      () => h(SettingsPage, { scope, locale }),
    ),
  )
}

      return { inject, apply }
    })()

    exports.apply = plugin.apply
    exports.inject = plugin.inject
    return module.exports
  },
})
