import { readFileSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

const root = new URL('../', import.meta.url)
const read = (name) => readFileSync(new URL(name, root), 'utf8')

const stripModuleSyntax = (source, label) => {
  const stripped = source
    .replace(/^\s*import\s[\s\S]*?from\s*['"][^'"]+['"]\s*;?[ \t]*$/gm, '')
    .replace(/^export\s+/gm, '')
  if (/^[ \t]*(import|export)\s/m.test(stripped)) {
    throw new Error(`${label}: module syntax survived inlining; extend stripModuleSyntax`)
  }
  return stripped.trim()
}

const MODULES = ['src/core.js', 'src/spend.js', 'src/money.js', 'src/i18n.js', 'src/client.js']

export const buildClientBundle = () => {
  const pkg = JSON.parse(read('package.json'))
  const inlined = MODULES.map((name) => stripModuleSyntax(read(name), name)).join('\n\n')

  return `/* GENERATED by scripts/build-client.mjs - do not edit. */
window.__ModuleLoader__.load({
  id: '${pkg.name}',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    const React = require('react')

    var plugin = (() => {
${inlined}

      return { inject, apply }
    })()

    exports.apply = plugin.apply
    exports.inject = plugin.inject
    return module.exports
  },
})
`
}

const isEntryPoint = process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href

if (isEntryPoint) {
  writeFileSync(new URL('client.js', root), buildClientBundle())
  console.log('[offpeak] built client.js')
}
